conky.config = {
  update_interval = 0.04,
  double_buffer = true,
  total_run_times = 0,

  own_window = true,
  own_window_type = 'desktop',
  own_window_transparent = true,
  own_window_argb_visual = true,
  own_window_argb_value = 0,
  own_window_class = 'conky_music',
  own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

  alignment = 'top_left',
  gap_x = 0,
  gap_y = 0,

  minimum_width = 2520,
  minimum_height = 1680,
  maximum_width = 2520,

  use_xft = true,
  xftalpha = 0.98,
  override_utf8_locale = true,

  lua_load = '/home/julie/.config/conky/music/main.lua',
  lua_draw_hook_pre = 'draw_all',

  out_to_x = true,
  out_to_console = false,
};

conky.text = [[
]];
